name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 14.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.1

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          
      - name: Install npm 6.14.13
        run: sudo npm install -g npm@6.14.13
          
      - name: Print npm version
        run: npm --version
      - name: Print node version
        run: node --version
      - name: Print mvn version
        run: mvn --version
        
      - name: Print mvn settings
        run: cat ~/.m2/settings.xml
          
#       - name: Build 'keystore-example'
#         run: mvn clean install -f common/keystore-example/pom.xml
#       - name: Build 'npmlib'
#         run: mvn clean install -f maven/npmlib/pom.xml 
#       - name: Build 'iac'
#         run: mvn clean install -f pom.xml 
#       - name: Build 'base-package'
#         run: mvn clean install -f maven/base-package/pom.xml
#       - name: Build 'packages'
#         run: mvn clean install -f packages/pom.xml 
#       - name: Build 'typescript-project-all'
#         run: mvn clean install -f maven/typescript-project-all/pom.xml 
#       - name: Build 'repository'
#         run: mvn clean install -f maven/repository/pom.xml 
      
