name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          
      - name: Build 'keystore-example'
        run: mvn clean install -f common/keystore-example/pom.xml
      - name: Build 'npmlib'
        run: mvn clean install -f maven/npmlib/pom.xml 
      - name: Build 'iac'
        run: mvn clean install -f pom.xml 
      - name: Build 'base-package'
        run: mvn clean install -f maven/base-package/pom.xml
      - name: Build 'packages'
        run: mvn clean install -f packages/pom.xml 
      - name: Build 'typescript-project-all'
        run: mvn clean install -f maven/typescript-project-all/pom.xml 
      - name: Build 'repository'
        run: mvn clean install -f maven/repository/pom.xml 
      
